---
# Disable ufw
- name: Disable ufw
  ansible.builtin.systemd:
    name: ufw
    state: stopped
    enabled: false


# Disable swap
- name: Disable swap
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb > 0

- name: Remove swapfile from /etc/fstab
  ansible.builtin.mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  with_items:
    - swap
    - none

- name: List systemctl swap targets
  ansible.builtin.command: systemctl --type swap --all --plain --no-legend
  register: systemctl_swap_raw

- name: Extract the first column from the list
  ansible.builtin.set_fact:
    systemctl_swap_targets: "{{ item.split()[0] }}"
  with_items:
    - "{{ systemctl_swap_raw.stdout_lines }}"

- name: Mask systemctl swap targets
  ansible.builtin.command: "systemctl mask {{ item }}"
  with_items:
    - "{{ systemctl_swap_targets }}"
  when: systemctl_swap_targets is defined