---
# Install common packages
- name: Install packages that allow apt to be used over HTTPS
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

# Install kube{let,adm,ctl}
- name: Add an apt signing key for Kubernetes
  ansible.builtin.apt_key:
    url: '{{ k8s_apt_gpg }}'
    state: present

- name: Adding apt repository for Kubernetes
  ansible.builtin.apt_repository:
    repo: '{{ k8s_apt_repository }}'
    state: present
    filename: kubernetes.list
    update_cache: true

- name: Install Kubernetes binaries
  ansible.builtin.apt: 
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - kubelet 
      - kubeadm 
      - kubectl

- name: Ensure kubelet is enabled
  ansible.builtin.systemd:
    name: kubelet
    state: started
    enabled: true

# Install iSCSI services
- name: Install Open iSCSI for PV
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - open-iscsi

- name: Enable service
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: open-iscsi
