---
# Install common packages
- name: Install packages that allow apt to be used over HTTPS
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

# Install Docker CE
- name: Add an apt signing key for the Docker
  ansible.builtin.apt_key:
    url: '{{ docker_apt_gpg }}'
    state: present

- name: Adding apt repository for the Docker
  ansible.builtin.apt_repository:
    repo: '{{ docker_apt_repository }}'
    state: present
    filename: docker.list
    update_cache: true

- name: Ensure Docker is installed.
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - docker-ce-cli
    - docker-buildx-plugin
    - docker-compose-plugin

- name: Ensure containerd service is restarted.
  ansible.builtin.systemd:
    name: docker
    state: started
    enabled: true