---
# Docker repository
docker_apt_gpg: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"

docker_apt_release_channel: stable
docker_apt_arch: '{{ (ansible_architecture == "aarch64") | ternary("arm64", "amd64") }}'
docker_apt_repository: "deb [arch={{ docker_apt_arch }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} {{ docker_apt_release_channel }}"
