---
- name: Reset all nodes used in kubernetes deployment
  hosts: nodes
  gather_facts: false
  become: true
  tasks:
    - name: Check if kubeadm is installed
      ansible.builtin.command: which kubeadm
      changed_when: false
      failed_when: kubeadm_installed.rc not in [0,1]
      register: kubeadm_installed
    - name: Reset kubeadm
      ansible.builtin.command: kubeadm reset -f
      register: kubeadm_reset
      when: kubeadm_installed.rc == 0
      changed_when: true
    - name: Print kubeadm output
      ansible.builtin.debug:
        var: kubeadm_reset
      when: kubeadm_installed.rc == 0
    - name: Remove CNI configuration
      ansible.builtin.file:
        state: absent
        path: /etc/cni/net.d/
